### ISSUE TITLE
Error while importing database schema

### ISSUE THREAD

**Issue by myownhost** [LordHepipud/icingaweb2-module-windows#1] opened 2018-11-29 14:47 UTC
Hello,
nice module. I try it on my test system.
I got the following errors at step:
`mysql -umyuser -p icinga_windows < /usr/share/icingaweb2/modules/windows/schema/mysql.sql`

```
ERROR 1067 (42000) at line 50: Invalid default value for 'timestamp'
ERROR 1101 (42000) at line 66: BLOB, TEXT, GEOMETRY or JSON column 'proc_cmd' can't have a default value
ERROR 1101 (42000) at line 286: BLOB, TEXT, GEOMETRY or JSON column 'help' can't have a default value
ERROR 1101 (42000) at line 294: BLOB, TEXT, GEOMETRY or JSON column 'network_addresses' can't have a default value
ERROR 1101 (42000) at line 313: BLOB, TEXT, GEOMETRY or JSON column 'dependent_services' can't have a default value
ERROR 1101 (42000) at line 313: BLOB, TEXT, GEOMETRY or JSON column 'service_handle' can't have a default value
ERROR 1101 (42000) at line 313: BLOB, TEXT, GEOMETRY or JSON column 'depends_on' can't have a default value
```

My environment is:
Ubuntu 16.04
MySQL 5.7
Icinga2 2.9
Icingaweb2 2.6.2

After some little modifications the import works:
```
54c54
<       `timestamp` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
---
>       `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
77c77
<   `proc_cmd` LONGTEXT NOT NULL DEFAULT '',
---
>   `proc_cmd` LONGTEXT NOT NULL,
290c290
<   `help` TEXT NOT NULL DEFAULT '',
---
>   `help` TEXT NOT NULL,
306c306
<   `network_addresses` TEXT NOT NULL DEFAULT '',
---
>   `network_addresses` TEXT NOT NULL,
317c317
<   `dependent_services` TEXT NOT NULL DEFAULT '',
---
>   `dependent_services` TEXT NOT NULL,
319,320c319,320
<   `service_handle` TEXT NOT NULL DEFAULT '',
<   `depends_on` TEXT NOT NULL DEFAULT '',
---
>   `service_handle` TEXT NOT NULL,
>   `depends_on` TEXT NOT NULL,
```

But now i got an error an agent error:

```
2018-29-11 15:45:22.994 [Debug]: {"status":"error","message":"SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'testclient.test.de', query was: UPDATE host_list SET os = :os, version = :version, port = :port WHERE host_id = 'testclient.test.de'"}
2018-29-11 15:45:22.996 [Debug]: Remote Server Output: 500
```

Many thanks for all your work.
Hopefully i don't forget any thing.

**Comment by LordHepipud** [comment] 2018-11-29 22:03
Hello and thank you very much for this issue.

I have already a local fix for this available, as I reworked plenty of parts - including the DB schema. A new version should be ready soon which will get rid of the DB errors and improves the schema and the web module itself.

**Comment by LordHepipud** [comment] 2018-12-06 16:19
Hello,

I just wanted to give an update on this. The current master should have fixed this issue, including a DB schema migration (identical to Icinga Director and vSphereDB Module).

The documentation has also been updated already: [Installation](https://github.com/LordHepipud/icingaweb2-module-windows/blob/master/doc/02-Installation.md)

Can you please try it with the current master and check if the issue is resolved in your case?

Thank you in advance.

**Closed as completed** 2019-05-03 12:54 UTC
Labels: bug
